/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface TweetData {
	/**
	 * This interface was referenced by `TweetData`'s JSON-Schema definition
	 * via the `patternProperty` "^[0-9a-zA-Z\-]+$".
	 */
	[k: string]: {
		game: string;
		category: string;
		content: string;
		media: string | null;
	};
}
